package org.palladiosimulator.editors.sirius.custom.style.styleconfiguration;

import org.eclipse.sirius.diagram.description.DiagramElementMapping;
import org.eclipse.sirius.diagram.ui.tools.api.graphical.edit.styles.IStyleConfigurationProvider;
import org.eclipse.sirius.diagram.ui.tools.api.graphical.edit.styles.StyleConfiguration;
import org.eclipse.sirius.viewpoint.Style;

/**
 * TODO autogenerated class to prevent exceptions (class was already referenced from extension point)
 * @author max
 *
 */
public class ResourceContainerStyleConfiguration implements IStyleConfigurationProvider {

	public ResourceContainerStyleConfiguration() {
		// TODO Auto-generated constructor stub
	}

	@Override
	public StyleConfiguration createStyleConfiguration(DiagramElementMapping arg0, Style arg1) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public boolean provides(DiagramElementMapping arg0, Style arg1) {
		// TODO Auto-generated method stub
		return false;
	}

}
