<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="architecturaltemplates" nsURI="http://scaledl.org/ArchitecturalTemplates/1.0"
    nsPrefix="org.scaledl">
  <eSubpackages name="type" nsURI="http://scaledl.org/ArchitecturalTemplates/Type/1.0"
      nsPrefix="org.scaledl.architecturaltemplates">
    <eClassifiers xsi:type="ecore:EClass" name="AT" eSuperTypes="platform:/plugin/org.palladiosimulator.pcm/model/pcm.ecore#//core/entity/Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="repository" lowerBound="1"
          eType="#//type/Repository" eOpposite="#//type/Repository/ATs"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="roles" upperBound="-1"
          eType="#//type/Role" containment="true" eOpposite="#//type/Role/AT"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
          eType="#//type/Constraint" containment="true" eOpposite="#//type/Constraint/AT"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="completion" lowerBound="1"
          eType="#//type/Completion" containment="true" eOpposite="#//type/Completion/AT">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="An Architectural Template needs exactly 1 completion for defining its semantics.&#xA;"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Constraint" abstract="true" eSuperTypes="platform:/plugin/org.palladiosimulator.pcm/model/pcm.ecore#//core/entity/Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="AT" lowerBound="1" eType="#//type/AT"
          eOpposite="#//type/AT/constraints"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="roles" upperBound="-1"
          eType="#//type/Role" eOpposite="#//type/Role/constraints"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="platform:/plugin/org.palladiosimulator.pcm/model/pcm.ecore#//core/entity/Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="role" lowerBound="1"
          eType="#//type/Role" eOpposite="#//type/Role/parameters"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dataType" lowerBound="1"
          eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDataType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Repository" eSuperTypes="platform:/plugin/org.palladiosimulator.pcm/model/pcm.ecore#//core/entity/Entity">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Allows to collect Architectural Templates within a catalogue."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ATs" upperBound="-1"
          eType="#//type/AT" containment="true" eOpposite="#//type/AT/repository"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Role" eSuperTypes="platform:/plugin/org.palladiosimulator.pcm/model/pcm.ecore#//core/entity/Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
          eType="#//type/Parameter" containment="true" eOpposite="#//type/Parameter/role"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="AT" lowerBound="1" eType="#//type/AT"
          eOpposite="#//type/AT/roles"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
          eType="#//type/Constraint" eOpposite="#//type/Constraint/roles"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="stereotype" lowerBound="1"
          eType="ecore:EClass platform:/plugin/org.modelversioning.emfprofile/model/emfprofiles.ecore#//Stereotype"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OCLConstraint" eSuperTypes="#//type/Constraint">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="constraint" lowerBound="1"
          eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="QVTOCompletion" eSuperTypes="#//type/Completion">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A completion realized as QVT Operational transformation"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="qvtoFileURI" lowerBound="1"
          eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Completion" abstract="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A completion is a refinement transformation from AT-annotated model into a model with well-defined semantics (thus, specifying the semantics of a given AT). This particularly includes a refinement transformation to another AT-annotated model as well (the second AT also includes a completion for defining its semantics, thus, has well-defined semantics).&#xA; &#xA;As an example, consider a component annotated with an AT role &quot;3-times loabalanced&quot;. A completion could refine this component into a model with 4 components: 1 loadbalancer plus 3 replica of the originally annotated component. The loadbalancer then evenly distributes load over the 3 replica."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="AT" lowerBound="1" eType="#//type/AT"
          eOpposite="#//type/AT/completion"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" lowerBound="1"
          upperBound="-1" eType="#//type/CompletionParameter" containment="true" eOpposite="#//type/CompletionParameter/completion">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Every in- and output parameter of a completion has to exactly match this order."/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CompletionParameter" abstract="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Completion parameters characterize the signatures of completions (i.e., the in- and output parameters of transformations)."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="completion" lowerBound="1"
          eType="#//type/Completion" eOpposite="#//type/Completion/parameters"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="GenericTemplateCompletionParameter"
        eSuperTypes="#//type/GenericBlackboardCompletionParameter #//type/TemplateProvidingEntity">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The input of a completion is an arbritrary model from a template and available via the MDSD blackboard."/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="GenericBlackboardCompletionParameter"
        eSuperTypes="#//type/CompletionParameter">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The input of a completion stems from the MDSD blackboard and is an arbitray model, characterized by the given file extension. The user can freely specify this extension as String."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileExtension" lowerBound="1"
          eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PCMBlackboardCompletionParameter"
        eSuperTypes="#//type/CompletionParameter">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The input of a completion stems from the MDSD blackboard and is a PCM model, characterized by its typical file extension. The user can select from available PCM extensions."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileExtension" lowerBound="1"
          eType="#//type/PCMFileExtensions"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="PCMFileExtensions">
      <eLiterals name="SYSTEM" literal="system"/>
      <eLiterals name="ALLOCATION" value="1" literal="allocation"/>
      <eLiterals name="RESOURCEENVIRONMENT" value="2" literal="resourceenvironment"/>
      <eLiterals name="REPOSITORY" value="3" literal="repository"/>
      <eLiterals name="USAGEMODEL" value="4" literal="usagemodel"/>
      <eLiterals name="RESOURCETYPE" value="5" literal="resourcetype"/>
      <eLiterals name="MONITORREPOSITORY" value="6" literal="monitorrepository"/>
      <eLiterals name="PCMMEASURINGPOINT" value="7" literal="pcmmeasuringpoint"/>
      <eLiterals name="SERVICELEVELOBJECTIVE" value="8" literal="slo"/>
      <eLiterals name="EXPERIMENTS" value="9" literal="experiments"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PCMTemplateCompletionParameter" eSuperTypes="#//type/PCMBlackboardCompletionParameter #//type/TemplateProvidingEntity">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The input of a completion is a PCM model from a template and available via the MDSD blackboard."/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TemplateProvidingEntity" abstract="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The input of a completion is based on a template model file."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="templateFileURI" lowerBound="1"
          eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PCMOutputCompletionParameter" eSuperTypes="#//type/CompletionParameter">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The output of a completion is a PCM model, characterized by its typical file extension. A user can select from available PCM extensions."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileExtension" lowerBound="1"
          eType="#//type/PCMFileExtensions"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="GenericOutputCompletionParameter"
        eSuperTypes="#//type/CompletionParameter">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The output of a completion is an arbitrary model, characterized by the given file extension. A user can freely specify this extension as String."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileExtension" lowerBound="1"
          eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="instance" nsURI="http://scaledl.org/ArchitecturalTemplates/Instance/1.0"
      nsPrefix="org.scaledl.architecturaltemplates">
    <eClassifiers xsi:type="ecore:EClass" name="ATInstance" eSuperTypes="platform:/plugin/org.palladiosimulator.pcm/model/pcm.ecore#//core/entity/Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="role2components" upperBound="-1"
          eType="#//instance/Role2Component" containment="true" eOpposite="#//instance/Role2Component/ATInstance"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="component2roles" upperBound="-1"
          eType="#//instance/Component2Role" containment="true" eOpposite="#//instance/Component2Role/ATInstance"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="AT2Components" lowerBound="1"
          eType="#//instance/Role2Component"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//type/AT"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameterValues" upperBound="-1"
          eType="#//instance/ParameterValue" containment="true" eOpposite="#//instance/ParameterValue/architecturalTemplateInstance"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="role2resources" upperBound="-1"
          eType="#//instance/Role2Resource" containment="true" eOpposite="#//instance/Role2Resource/ATInstance"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Component2Role">
      <eStructuralFeatures xsi:type="ecore:EReference" name="component" lowerBound="1"
          eType="ecore:EClass platform:/plugin/org.palladiosimulator.pcm/model/pcm.ecore#//core/composition/AssemblyContext"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="roles" upperBound="-1"
          eType="#//type/Role"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ATInstance" lowerBound="1"
          eType="#//instance/ATInstance" eOpposite="#//instance/ATInstance/component2roles"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Role2Component">
      <eStructuralFeatures xsi:type="ecore:EReference" name="component" lowerBound="1"
          eType="ecore:EClass platform:/plugin/org.palladiosimulator.pcm/model/pcm.ecore#//core/composition/AssemblyContext"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="role" lowerBound="1"
          eType="#//type/Role"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ATInstance" lowerBound="1"
          eType="#//instance/ATInstance" eOpposite="#//instance/ATInstance/role2components"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ParameterValue" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//type/Parameter"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="architecturalTemplateInstance"
          lowerBound="1" eType="#//instance/ATInstance" eOpposite="#//instance/ATInstance/parameterValues"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EnumParameter" eSuperTypes="#//instance/ParameterValue"/>
    <eClassifiers xsi:type="ecore:EClass" name="IntegerParameter" eSuperTypes="#//instance/ParameterValue"/>
    <eClassifiers xsi:type="ecore:EClass" name="FloatParameter" eSuperTypes="#//instance/ParameterValue"/>
    <eClassifiers xsi:type="ecore:EClass" name="StringParameter" eSuperTypes="#//instance/ParameterValue">
      <eTypeParameters name="T"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Role2Resource">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ATInstance" lowerBound="1"
          eType="#//instance/ATInstance" eOpposite="#//instance/ATInstance/role2resources"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="resource" lowerBound="1"
          eType="ecore:EClass platform:/plugin/org.palladiosimulator.pcm/model/pcm.ecore#//resourceenvironment/ResourceContainer"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="role" lowerBound="1"
          eType="#//type/Role"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
