/**
 */
package org.scaledl.architecturaltemplates.instance.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;
import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;
import org.scaledl.architecturaltemplates.instance.util.InstanceAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers. The
 * adapters generated by this factory convert EMF adapter notifications into calls to
 * {@link #fireNotifyChanged fireNotifyChanged}. The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances. <!-- begin-user-doc --> <!--
 * end-user-doc -->
 *
 * @generated
 */
public class InstanceItemProviderAdapterFactory extends InstanceAdapterFactory implements ComposeableAdapterFactory,
        IChangeNotifier, IDisposable {
    /**
     * This keeps track of the root adapter factory that delegates to this adapter factory. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    protected ComposedAdapterFactory parentAdapterFactory;

    /**
     * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    protected IChangeNotifier changeNotifier = new ChangeNotifier();

    /**
     * This keeps track of all the supported types checked by {@link #isFactoryForType
     * isFactoryForType}. <!-- begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    protected Collection<Object> supportedTypes = new ArrayList<Object>();

    /**
     * This constructs an instance. <!-- begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    public InstanceItemProviderAdapterFactory() {
        this.supportedTypes.add(IEditingDomainItemProvider.class);
        this.supportedTypes.add(IStructuredItemContentProvider.class);
        this.supportedTypes.add(ITreeItemContentProvider.class);
        this.supportedTypes.add(IItemLabelProvider.class);
        this.supportedTypes.add(IItemPropertySource.class);
    }

    /**
     * This keeps track of the one adapter used for all
     * {@link org.scaledl.architecturaltemplates.instance.ATInstance} instances. <!-- begin-user-doc
     * --> <!-- end-user-doc -->
     *
     * @generated
     */
    protected ATInstanceItemProvider atInstanceItemProvider;

    /**
     * This creates an adapter for a {@link org.scaledl.architecturaltemplates.instance.ATInstance}.
     * <!-- begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createATInstanceAdapter() {
        if (this.atInstanceItemProvider == null) {
            this.atInstanceItemProvider = new ATInstanceItemProvider(this);
        }

        return this.atInstanceItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all
     * {@link org.scaledl.architecturaltemplates.instance.Component2Role} instances. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    protected Component2RoleItemProvider component2RoleItemProvider;

    /**
     * This creates an adapter for a
     * {@link org.scaledl.architecturaltemplates.instance.Component2Role}. <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createComponent2RoleAdapter() {
        if (this.component2RoleItemProvider == null) {
            this.component2RoleItemProvider = new Component2RoleItemProvider(this);
        }

        return this.component2RoleItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all
     * {@link org.scaledl.architecturaltemplates.instance.Role2Component} instances. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    protected Role2ComponentItemProvider role2ComponentItemProvider;

    /**
     * This creates an adapter for a
     * {@link org.scaledl.architecturaltemplates.instance.Role2Component}. <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createRole2ComponentAdapter() {
        if (this.role2ComponentItemProvider == null) {
            this.role2ComponentItemProvider = new Role2ComponentItemProvider(this);
        }

        return this.role2ComponentItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all
     * {@link org.scaledl.architecturaltemplates.instance.EnumParameter} instances. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    protected EnumParameterItemProvider enumParameterItemProvider;

    /**
     * This creates an adapter for a
     * {@link org.scaledl.architecturaltemplates.instance.EnumParameter}. <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createEnumParameterAdapter() {
        if (this.enumParameterItemProvider == null) {
            this.enumParameterItemProvider = new EnumParameterItemProvider(this);
        }

        return this.enumParameterItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all
     * {@link org.scaledl.architecturaltemplates.instance.IntegerParameter} instances. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    protected IntegerParameterItemProvider integerParameterItemProvider;

    /**
     * This creates an adapter for a
     * {@link org.scaledl.architecturaltemplates.instance.IntegerParameter}. <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createIntegerParameterAdapter() {
        if (this.integerParameterItemProvider == null) {
            this.integerParameterItemProvider = new IntegerParameterItemProvider(this);
        }

        return this.integerParameterItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all
     * {@link org.scaledl.architecturaltemplates.instance.FloatParameter} instances. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    protected FloatParameterItemProvider floatParameterItemProvider;

    /**
     * This creates an adapter for a
     * {@link org.scaledl.architecturaltemplates.instance.FloatParameter}. <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createFloatParameterAdapter() {
        if (this.floatParameterItemProvider == null) {
            this.floatParameterItemProvider = new FloatParameterItemProvider(this);
        }

        return this.floatParameterItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all
     * {@link org.scaledl.architecturaltemplates.instance.StringParameter} instances. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    protected StringParameterItemProvider stringParameterItemProvider;

    /**
     * This creates an adapter for a
     * {@link org.scaledl.architecturaltemplates.instance.StringParameter}. <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createStringParameterAdapter() {
        if (this.stringParameterItemProvider == null) {
            this.stringParameterItemProvider = new StringParameterItemProvider(this);
        }

        return this.stringParameterItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all
     * {@link org.scaledl.architecturaltemplates.instance.Role2Resource} instances. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    protected Role2ResourceItemProvider role2ResourceItemProvider;

    /**
     * This creates an adapter for a
     * {@link org.scaledl.architecturaltemplates.instance.Role2Resource}. <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter createRole2ResourceAdapter() {
        if (this.role2ResourceItemProvider == null) {
            this.role2ResourceItemProvider = new Role2ResourceItemProvider(this);
        }

        return this.role2ResourceItemProvider;
    }

    /**
     * This returns the root adapter factory that contains this factory. <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public ComposeableAdapterFactory getRootAdapterFactory() {
        return this.parentAdapterFactory == null ? this : this.parentAdapterFactory.getRootAdapterFactory();
    }

    /**
     * This sets the composed adapter factory that contains this factory. <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public void setParentAdapterFactory(final ComposedAdapterFactory parentAdapterFactory) {
        this.parentAdapterFactory = parentAdapterFactory;
    }

    /**
     * <!-- begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public boolean isFactoryForType(final Object type) {
        return this.supportedTypes.contains(type) || super.isFactoryForType(type);
    }

    /**
     * This implementation substitutes the factory itself as the key for the adapter. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Adapter adapt(final Notifier notifier, final Object type) {
        return super.adapt(notifier, this);
    }

    /**
     * <!-- begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public Object adapt(final Object object, final Object type) {
        if (this.isFactoryForType(type)) {
            final Object adapter = super.adapt(object, type);
            if (!(type instanceof Class<?>) || (((Class<?>) type).isInstance(adapter))) {
                return adapter;
            }
        }

        return null;
    }

    /**
     * This adds a listener. <!-- begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public void addListener(final INotifyChangedListener notifyChangedListener) {
        this.changeNotifier.addListener(notifyChangedListener);
    }

    /**
     * This removes a listener. <!-- begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public void removeListener(final INotifyChangedListener notifyChangedListener) {
        this.changeNotifier.removeListener(notifyChangedListener);
    }

    /**
     * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}. <!--
     * begin-user-doc --> <!-- end-user-doc -->
     *
     * @generated
     */
    @Override
    public void fireNotifyChanged(final Notification notification) {
        this.changeNotifier.fireNotifyChanged(notification);

        if (this.parentAdapterFactory != null) {
            this.parentAdapterFactory.fireNotifyChanged(notification);
        }
    }

    /**
     * This disposes all of the item providers created by this factory. <!-- begin-user-doc --> <!--
     * end-user-doc -->
     *
     * @generated
     */
    @Override
    public void dispose() {
        if (this.atInstanceItemProvider != null) {
            this.atInstanceItemProvider.dispose();
        }
        if (this.component2RoleItemProvider != null) {
            this.component2RoleItemProvider.dispose();
        }
        if (this.role2ComponentItemProvider != null) {
            this.role2ComponentItemProvider.dispose();
        }
        if (this.enumParameterItemProvider != null) {
            this.enumParameterItemProvider.dispose();
        }
        if (this.integerParameterItemProvider != null) {
            this.integerParameterItemProvider.dispose();
        }
        if (this.floatParameterItemProvider != null) {
            this.floatParameterItemProvider.dispose();
        }
        if (this.stringParameterItemProvider != null) {
            this.stringParameterItemProvider.dispose();
        }
        if (this.role2ResourceItemProvider != null) {
            this.role2ResourceItemProvider.dispose();
        }
    }

}
